language: java
sudo: false
jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
    - nmap

# setup jobs.
env:
 - _JAVA_OPTIONS= "-Djava.awt.headless=true"
 
before_install:
  - pip install --user codecov

after_success:
  - codecov
  
